# Generated by Django 5.1.1 on 2024-09-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('grado', models.IntegerField()),
                ('fecha_nacimiento', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
